import type { Metadata } from 'next'
import './globals.css'

import ClientLayout from '@/client-layout'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "T'as la ref ?",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Toaster />
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
